[book]
#  This book is called
title = "Rust 中的命令列應用程式"
# ...but friends call it "Clair"
authors = ["The Rust CLI Working Group"]
multilingual = false
language = "en"
src = "src"

[output.html]
curly-quotes = true
additional-css = ["src/special-content.css"]
git-repository-url = "https://github.com/rust-cli/book"
site-url = "/book/"

# Linkcheck doesn't find images/SVG so it's not enabled for now
# [output.linkcheck]
